{
 "title": "Dynamic filtering",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current delay (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "delay", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Dropped events / s",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(dropped_events_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropping percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "dropping_percentage{application_name=\"dynamicfiltering\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed events / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(processed_events_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}